### ISSUE TITLE
Conductor or Phoenix

### ISSUE THREAD

**Issue by alexg0** [keith/conductor#4]
The repo at https://github.com/kasper/phoenix has newer code and is at a higher version (2.0 vs 1.2.1).    What is the relationship and development status of Phoenix vs Conductor?

**Comment by keith** [comment]
I forked that repo in September of last year. I chose to do that since the maintainer at the time actively didn't want to make distribution easy for users. I did a ton of code cleanup and added an API for brightness. I had to change the name so that I could distribute it via homebrew cask. Since phoneix belonged to the other repo. It doesn't look like much has changed on that repo in the meantime, it looks like the 2.0 version number was jumped to when maintainers switched again. Right now besides the single API I added and the name differences the functionality is pretty similar. I'm not sure if the other maintainer plans to continue adding features in the future since many users have switched to hammerspoon. I'm happily using conductor and plan to continue maintaining it for my own personal use. I don't feel the need for anything more complex than conductor at the moment.

**Comment by alexg0** [comment]
Thanks for clarifying.  Lack of cask support homebrew cask support would be a stopper.

**Comment by keith** [comment]
Well you can do a `brew cask install conductor` now. I'm not sure what the state of Phoenix is in that regard.

**Comment by kasper** [comment]
Hi! Not trying to be annoying, but you seem to have removed the original license completely from this fork? (cc @jasonm23)

**Comment by keith** [comment]
@kasper you're right. I've updated the LICENSE file with the other copyrights https://github.com/keith/conductor/commit/0d629e7b0dcdc9dadbc59a27f4ba19c186cbe26c note this was the same license copy since I forked the repo.

Thanks!

**Comment by kasper** [comment]
@keith Great, thanks!

**Comment by jasonm23** [comment]
We do have a slight problem here.  Conductor should not have been using Phoenix's logo.

You'll need to remove the logo/icon designs and replace them with something else. It should happen immediately.

I never authorised this, and more importantly it confuses users as to which product is which.

**Comment by keith** [comment]
I was under the impression the icon was under the same license as the project itself, seeing as it was submitted under that license. I'm happy to remove it though. The only reason I haven't changed it is because I've put off trying to find a replacement.

Also worth noting that this repo really was just meant to be a detached fork of phoenix. The only reason I changed the name was because of the conflict when submitting to homebrew-cask.

**Comment by jasonm23** [comment]
Well it's much more about identity of Phoenix and which one is genuine ;)

How do you feel about merging back into Phoenix now Keith?

We can look at the features you added, and reimplement things that are being used in your and end user configs.

There will be some API inconsistency due to Kasper's overhaul, but I think it would be worth it to reunify the product for the community.

**Comment by kasper** [comment]
@jasonm23 Technically the logo is under the MIT-license, but this definitely can cause confusion as is evident by this thread. Especially, since the logo is used with a different name and this is not a genuine fork anymore. This is probably the biggest concern, in addition to the already fixed original license. So I concur with this sentiment. Personally, I’m totally fine with a fork or reuse of the code, especially since it is very detached from the current state.

**Comment by jasonm23** [comment]
The Logo rights were assigned to the Phoenix project specifically and are separate IP property.

This should be stated more explicitly in the LICENCE, but that's the way it was done.

I'm the designer of the Logo, and that's how I assigned the licence to Steve.  These agreements and communications were done via email though, so the confusion is completely understandable.

**Comment by kasper** [comment]
@jasonm23 Ah, good to know! I’ll amend the license for this part.

**Comment by keith** [comment]
I actually removed the icon last night, so regardless of the licensing issues we should be good here: https://github.com/keith/conductor/commit/b04e089bba507593eb29ee37186aae2e38ae374a
